### ISSUE TITLE
psreadline multi-line problem with chinese heiti font family

### ISSUE THREAD

**Issue by chuanjiao10** [lzybkr/PSReadLine#542]
I think:
chinese heiti font family is default on windows,in the high-resolution display is beautiful.
Can not restrict user terminal software default font. 

Steps to reproduce
------------------

1Run terminal software:putty or xshell

2Choose font name 'heiti' or 'microsoft yahei mono' 

3Connect to linux and run powershell.

4Paste the following order and press Enter 3 --- 5 times.
Get-StringHash -Text 'powershell躺着进行数值计算' 

look： 
The phenomenon only appeared at this time:when psreadline + heiti font + past chinese string on linux.
No problem when press up key,run the history command.
No problem with songti family,eg:新宋体
No problem when remove-module psreadline
No problem on windows + powershell.only terminal software + powershell core.

Actual behavior
---------------

Environment data
----------------

Os:from windows 10
Terminal software:putty and xshell
Font:chinese heiti,microsoft yahei mono
Linux:

Name                           Value                                                                                                             
----                           -----                                                                                                             
PSVersion                      6.0.0-beta                                                                                                        
PSEdition                      Core                                                                                                              
BuildVersion                   3.0.0.0                                                                                                           
CLRVersion                                                                                                                                       
GitCommitId                    v6.0.0-beta.2                                                                                                     
OS                             Linux 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017                                              
Platform                       Unix                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                               
SerializationVersion           1.1.0.1                                                                                                           
WSManStackVersion              3.0 

psreadline:
Major  Minor  Build  Revision
-----  -----  -----  --------
1      2      -1     -1      

reporter
----------------
By the chinese powershell study & research group. QQ group No. is 183173532

in 'vscode' or other open source project,in version release notes,bug reporter should be thank.
So I left a group name.

**Comment by chuanjiao10** [comment]
![mypsreadline5](https://user-images.githubusercontent.com/8968667/27278748-e9dc230a-5514-11e7-9109-8f8d288afdfe.GIF)

**Comment by lzybkr** [comment]
I'm not sure I totally understand the issue, but I did fix another CJK issue, so I hope this is fixed by #561.

I'll publish a pre-release version to the PowerShell Gallery as soon as they support pre-releases.

If you'd like to try a fix before that, you can build the lastest yourself from the master branch, or 
grab a build from AppVeyor like this [one](https://ci.appveyor.com/api/buildjobs/ust6h6k216i5gm81/artifacts/bin%2FRelease%2FPSReadline.zip).

Note the version number is now 2.0, so be sure to copy the contents to <Your module dir>\PSReadLine\2.0.

**Comment by chuanjiao10** [comment]
1 run the code "Get-StringHash -Text 'powershell躺着进行数值计算'" in powershell core 6.0 beta8 in centos7.


2 download the zip,then put it into '/opt/microsoft/powershell/6.0.0-beta.8/Modules/PSReadLine/2.0'
ls -l '/opt/microsoft/powershell/6.0.0-beta.8/Modules/PSReadLine/2.0'           ```                                                                    
总用量 324
-rw-r--r--. 1 root root  12418 10月 17 09:46 Changes.txt
drwxr-xr-x. 2 root root   4096 10月 17 09:46 en-US
-rw-r--r--. 1 root root   1300 10月 17 09:46 License.txt
-rw-r--r--. 1 root root 221696 10月 17 09:46 Microsoft.PowerShell.PSReadLine.dll
-rw-r--r--. 1 root root   5730 10月 17 09:46 PSReadLine.format.ps1xml
-rw-r--r--. 1 root root    792 10月 17 09:46 PSReadLine.psd1
-rw-r--r--. 1 root root    175 10月 17 09:46 PSReadLine.psm1
-rw-r--r--. 1 root root  20813 10月 17 09:46 SamplePSReadlineProfile.ps1
-rw-r--r--. 1 root root  33256 10月 17 09:46 System.Runtime.InteropServices.RuntimeInformation.dll
```

3 restart my vm,powershell,run the code 
4 Multi lines still from the code, the third time.
Return change:
heiti font family and songti font family are so

Environment change:
powershell core 6.0 beta2  ---->   6.0 beta8
centos7 7.3 1611 ---->  centos7 7.4 1708 

note:
restart terminal software mybe needed.

**Comment by lzybkr** [comment]
I don't think PowerShell Core will load new versions of PSReadLine that way because it has a "trusted platform assembly".

You need to replace these files:
```
/opt/microsoft/powershell/6.0.0-beta.8/Microsoft.PowerShell.PSReadLine.dll
/opt/microsoft/powershell/6.0.0-beta.8/Modules/PSReadLine/PSReadLine.psd1
```

And add:

```
/opt/microsoft/powershell/6.0.0-beta.8/Modules/PSReadLine/PSReadLine.format.ps1xml
```

After replacing those files, you can verify you have the latest version with: `Get-Module PSReadLine`, it should report 2.0. Another check, the following should be true:

```
PS> (Get-PSReadlineOption).CommandColor[0] -eq 0x1b
True
```

**Comment by chuanjiao10** [comment]
yes, fixed!
bug paste into command line Garbled.
============
xshell + heiti font family 


![xshell](https://user-images.githubusercontent.com/8968667/31649857-6c37a14a-b347-11e7-8e7d-05b5443194dc.png)

============
putty 0.70 + default font (songti font family)
![putty](https://user-images.githubusercontent.com/8968667/31649843-5db4251c-b347-11e7-98f8-78c5fc65718b.png)

**Comment by lzybkr** [comment]
Odd.  It looks like the error message has the correct text which means PowerShell received the right input. I'm guessing it isn't paste then - do you see the same thing when typing?

I wonder what might be wrong. Maybe PSReadLine is setting the wrong code page? I think the fix was setting the output encoding to Unicode, at least that was the fix on Windows.

FWIW, pasting on Windows works correctly with the KaiTi or NSimSun fonts

**Comment by chuanjiao10** [comment]
do you see the same thing when typing? 
-------yes.command line type chinese letter Garbled.
remove-module psreadline,then typing,normal.

**Comment by lzybkr** [comment]
Hopefully this is fixed now - reactivate if not. I made one relevant change that was affecting Linux in other ways - I switched from Unicode to UTF8 output - hopefully that fixes the problem you were seeing too.

I'll have an official prerelease build out next week if you want to verify this is fixed, otherwise you can grab a build out of appveyor [here](https://ci.appveyor.com/project/lzybkr/psreadline).

**Comment by chuanjiao10** [comment]
YES,i tested,it fixed!
Good job,thank you!
